version: "2"

options:
  compose-file-path: 'docker-compose.yml'
  verbose: true
syncs:
  dotnet-dev-sync:
    src: '../app'
    sync_strategy: 'unison'
    sync_args: '-prefer newer'
    sync_prefer: 'default'
    watch_args: '-v'
